FROM node:12.2.0-alpine
LABEL maintainer="jose.duran@duransoftware.es"
LABEL description="SQL Query api"
LABEL version="1.0.0"

RUN mkdir /app
RUN mkdir /app/node_modules

WORKDIR .

ADD ./docker/dssqlqueryapi.js ./app/ 
	ADD node_modules/ ./app/node_modules/


WORKDIR ./app

RUN ls -la /app/*




EXPOSE 51240
CMD ["node", "dssqlqueryapi.js"]
